### ISSUE TITLE
能加个ddns-go可选项吗

### ISSUE THREAD

**Issue by KiritanTakechi** [sbwml/r4s_build_script#11]
rt

**Comment by KiritanTakechi** [comment]
luci-app-ddns-go

**Comment by sbwml** [comment]
02 脚本自己可以添加源码的拉取操作   common-config   添加目标插件 =y 即可

发自我的iPhone

**Comment by KiritanTakechi** [comment]
插件id有什么可以方便获取的吗我看插件里面makefile没有

**Comment by KiritanTakechi** [comment]
对了，这个默认支持nginx ssl连接吗

**Comment by KiritanTakechi** [comment]
不支持的话我把nginx-ssl加上，配置文件是uci.conf是吧

**Comment by sbwml** [comment]
这个固件默认编译全模块nginx，并支持 quic 协议。

发自我的iPhone

**Comment by KiritanTakechi** [comment]
默认好像没开https，我在uci.conf里面加上443 server块好像也不起作用，怎么打开https的？求

**Comment by sbwml** [comment]
openwrt 的使用，建议看官方文档。
