### ISSUE TITLE
默认版的插件有点太多了~想精简掉一些用不到的

### ISSUE THREAD

**Issue by Pacio** [sbwml/r4s_build_script#13]
直接在common-config里面注释掉（#）对应的插件可以吗？

**Comment by sbwml** [comment]
可以

**Comment by Pacio** [comment]
官方这个23.05.2 版本是不是upnp有问题啊~之前用lede编译~什么都不用设置，docker里面跑的网心云自动就是全锥型~换了这个怎么设置都显示端口限制

**Comment by sbwml** [comment]
首先 upnp 和 fullcone 是两种东西，它们在 23.05 上均工作（应该自己去测试）

至于你说的某 docker 应用显示限制型，你应该找联系这个应用的开发。

不排除 CG & FW4 的缘故，如果真实情况由你所说，那么 openwrt 22.03 以上都不适合你。你只能去用 openwrt 老版本 21.02 以下 或你说的 lede。

发自我的Apple Watch
