### ISSUE TITLE
求助，mini版本，装了openclash后，ddns公网ip一直变

### ISSUE THREAD

**Issue by new1943** [sbwml/r4s_build_script#15]
求助，mini版本，很满意，我只需要一个干净的openwrt，你这个最符合了。然后装了openclash。之前用istoreos的时候，外网访问正常的。咱们的版本，我看了下群晖的ddns上的信息，公网一直变来变去的。这个是我配置的问题么？

**Comment by sbwml** [comment]
你科学配置的问题，你得把群晖检测公网IP 的链接添加到白名单（即不让它走代理）

或者直接使用 openwrt 自带的国内 ddns，比如阿里云、腾讯云（dnspod），科学什么都不用做，它也可以正确工作
