### ISSUE TITLE
能添加网件的A6210的驱动吗？

### ISSUE THREAD

**Issue by cloudysky9** [sbwml/r4s_build_script#17]
能添加网件A6210USB网卡的驱动吗？我在后台的页面的软件包里添加mt7612u的驱动不管用，无法显示无线选项。

**Comment by sbwml** [comment]
无线驱动安装后你需要重启机器才会生成无线的配置文件，之后你才能在openwrt luci 上看到无线选项

**Comment by cloudysky9** [comment]
重启过的，拔电重启和后台页面重启选项重启全部试过，依然没有无线选项，然后我又重新下载系统镜像重新写盘开机，下载驱动后插入网卡重启依然没有看到无线选项

**Comment by sbwml** [comment]
在以往的测试中，安装 `kmod-mt76x2u` 重启机器就会生成配置文件 `/etc/config/wireless`，你必须确保你的无线卡它在 openwrt 中是正常被识别到的，使用命令 `lsusb` 验证（有或没有它正常情况下都会显示插入的 usb无线设备）。
