### ISSUE TITLE
boot failure

### ISSUE THREAD

**Issue by minkoonim** [sbwml/r4s_build_script#19]
3/21的最新版本，
刷上去好像系统启动失败，
连显示器也看不到啥

**Comment by sbwml** [comment]
你用的是老掉牙的cpu？

**Comment by minkoonim** [comment]
> [f58d7f3](https://github.com/sbwml/r4s_build_script/commit/f58d7f3f210f518b33e8b61fb017d915d8c2bcc6) 回滚老掉牙cpu的支持了。我是实在没想到2024年，还有不支持v3微架构的cpu在服役

我用的N6005 
老掉牙是啥 名字好可爱 哈哈哈
