### ISSUE TITLE
编译完成后的网络问题

### ISSUE THREAD

**Issue by kufei326** [sbwml/r4s_build_script#20]
config device
	option name 'br-lan'
	option type 'bridge'
	list ports 'eth1'
这里一直是eth1，用虚拟机装好了每次都要修改成eth0才可以进web管理

**Comment by sbwml** [comment]
这是预期行为，因为 eth0 默认是 wan，eth1 是 lan。因为x86 的设备种类繁多，没有网口统一的标准。

虚拟机安装你可以使用VM的桥接网络模式，openwrt 只需要允许防火墙 wan 区域的 input 流量，就可以通过它dhcp 获取的 ip 进入后台。

**Comment by kufei326** [comment]
感谢你的回复，我是用lxc安装的，能否告知在哪里修改

**Comment by kufei326** [comment]
感谢您的回复，才开始学编译op，我克隆了一个仓库试着修改wan口不过编译错误sed -i 's|uci set network.globals.packet_steering=1|&\nuci add_list network.@device[-1].ports='\''eth0'\''|' package/new/default-settings/default/zzz-default-settings
我在脚本里面尝试在初始设置里面修改成eth0，不过编译错误了

**Comment by kufei326** [comment]
找到了，感谢您的耐心回答，主要是用lxc安装op搭建emby硬解码方便，而且我gd网盘有资源，有科学也很方便
