### ISSUE TITLE
必须要更新内核才可以编译吗？

### ISSUE THREAD

**Issue by kufei326** [sbwml/r4s_build_script#21]
看你仓库更新到6.23了，我的还是6.22的，一直都是
ERROR: toolchain/kernel-headers failed to build.失败

**Comment by sbwml** [comment]
https://github.com/sbwml/r4s_build_script/commits/master/

![image](https://github.com/sbwml/r4s_build_script/assets/16485166/35811e12-d117-47ae-b50c-1f140558ecc8)

**Comment by sbwml** [comment]
`sbwml/r4s_build_script`  这个 repo 它是脱离 openwrt 官方的内核构造，如果基于这个 repo 去编译，必须与我的最新提交同步，因为它不仅仅是一次 commit 的改变，而是一系列关联的库都会发生改变。

所以我一直说 fork 项目，而不是独立自建项目。因为fork 的 repo github支持一键同步上游
