### ISSUE TITLE
好像docker网络有问题..?

### ISSUE THREAD

**Issue by minkoonim** [sbwml/r4s_build_script#22]
菜单 - docker - 网络
会出现这个错误页面

![image](https://github.com/sbwml/r4s_build_script/assets/38183949/faa2e019-206c-4a8f-967c-39fa4c430d61)

**Comment by sbwml** [comment]
已修复，三个小时内会得到固件ota

**Comment by minkoonim** [comment]
> 已修复，三个小时内会得到固件ota

你超棒最棒最好谢谢你比心
