### ISSUE TITLE
REQ: Add Banana Pi BPI-R4

### ISSUE THREAD

**Issue by mdsdtech** [sbwml/r4s_build_script#24]
Hi Bard,

Sorry for asking. Can you add this device into the firmware build?

Thank you.

**Comment by sbwml** [comment]
This is an officially supported device for OpenWrt: https://downloads.openwrt.org/snapshots/targets/mediatek/filogic/

The file I have here is a personalized openwrt build for my own device, not a generic build script. Although adding an officially supported device to this script is a simple matter, it doesn't make much sense. I can't do much more for unknown devices than simply "build" them. It's better to use the official openwrt firmware directly.
