### ISSUE TITLE
请教一个openssl quic的问题

### ISSUE THREAD

**Issue by lwb1978** [sbwml/r4s_build_script#25]
@sbwml  想跟大佬请教或者探讨一下openssl quic的问题。当前curl8.7依赖ngtcp2，而ngtcp2编译时需要quic，目前官方仓库和immortal仓库里23.05和主线分支都是的openssl 3.0，需要而外打补丁才能支持quic，如果不打补丁的话便于ngtcp2是会报错的。我近日从lede转到imm的时候就没编译通过，搞了几小时，最后还是在贵宝地找到了openssl的quic补丁打上去才完成编译。我现在搞不清楚的是难道用官方或者imm版本的人都不用curl的吗？在官方和imm明知问题也不提供补丁也不升级openssl到3.2时，大家都是自行解决的吗？

**Comment by sbwml** [comment]
openwrt 的 curl quic 支持实际上是一个错误提交。你只要不选添加 ngtcp2 支持就不会编译出错。

发自我的iPhone

**Comment by lwb1978** [comment]
主要是有强迫症，还好你这里找到了补丁。没想到官方也这么不严谨，我在lede中添加curl8.7是自己修改了makefile，去掉了nghttp3和ngtcp2的依赖。本以为我编译官方版本是哪里姿势不对，没想到是错误提交，而且还不修正，服了。
