### ISSUE TITLE
X86有没有用clang lto优化？

### ISSUE THREAD

**Issue by shuangqiao999** [sbwml/r4s_build_script#30]

**Comment by sbwml** [comment]
自己编译需要开启，直接下载我GitHub的固件默认已经开启

发自我的iPhone

**Comment by shuangqiao999** [comment]
通过ssh修改网卡tx/rx缓冲值 重启又恢复了默认值 这个要怎么修改才能在重启后生效？

**Comment by sbwml** [comment]
> 通过ssh修改网卡tx/rx缓冲值 重启又恢复了默认值 这个要怎么修改才能在重启后生效？

OpenWrt LuCI 自带的“启动项” 可能会帮到你。在本地启动脚本 exit 0 上面添加你的命令

**Comment by shuangqiao999** [comment]
感谢🙏🙏🙏 迷你版真的很好用
