### ISSUE TITLE
借宝地请教，关于dns2tcp采用二进制编译

### ISSUE THREAD

**Issue by lwb1978** [sbwml/r4s_build_script#34]
前两天PW的依赖库更新了dns2tcp到1.1.1，发现有人反馈mips编译报错：
https://github.com/xiaorouji/openwrt-passwall-packages/issues/225

我看了dns2tcp的仓库提供了比较全面的二进制文件，想着应该可以采用二进制的方式编译，但是我对makefile不是很了解，所以参考了你的chinadns-ng修改了一个dns2tcp的makefile，发到贵地，老大有空帮看看是否有错，还有哪里需要完善的不，谢谢。

[Makefile.txt](https://github.com/sbwml/r4s_build_script/files/15446245/Makefile.txt)

**Comment by sbwml** [comment]
c 语言程序使用二进制。这是徒增烦恼

**Comment by lwb1978** [comment]
明白了，谢谢。

**Comment by sbwml** [comment]
我能帮到的   只有这么多   https://github.com/sbwml/openwrt_helloworld/commit/b1d49a6112fd3626ce0b28394f9ecd6191f61311
