### ISSUE TITLE
使用dpdk路由器性能会更好吗？

### ISSUE THREAD

**Issue by shuangqiao999** [sbwml/r4s_build_script#36]

**Comment by sbwml** [comment]
我不是Google、维基百科

Closed #36

从 Windows 版邮件发送

发件人: shuangqiao999
发送时间: 2024年6月6日 20:36
收件人: sbwml/r4s_build_script
抄送: Subscribed
主题: [sbwml/r4s_build_script] 使用dpdk路由器性能会更好吗？ (Issue #36)
