### ISSUE TITLE
你好 Actions如果只需要x86 要修改哪里啊？

### ISSUE THREAD

**Issue by shuangqiao999** [sbwml/r4s_build_script#37]

**Comment by sbwml** [comment]
晚些时候我会更新任务流允许运行指定 device

从 Windows 版邮件发送

发件人: shuangqiao999
发送时间: 2024年6月29日 9:45
收件人: sbwml/r4s_build_script
抄送: Subscribed
主题: [sbwml/r4s_build_script] 你好 Actions如果只需要x86 要修改哪里啊？ (Issue #37)

**Comment by shuangqiao999** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
