### ISSUE TITLE
你好 为什么使用glibc会编译失败？

### ISSUE THREAD

**Issue by shuangqiao999** [sbwml/r4s_build_script#38]

**Comment by sbwml** [comment]
不知道

如果你解决不了问题，那你可以直接下载  https://github.com/sbwml/openwrt_with_glibc/releases/tag/v23.05.3

发自我的iPhone

**Comment by shuangqiao999** [comment]
> 不知道
> 
> 如果你解决不了问题，那你可以直接下载  https://github.com/sbwml/openwrt_with_glibc/releases/tag/v23.05.3
> 
> 发自我的iPhone
> 
> > 在 2024年7月1日，02:34，shuangqiao999 ***@***.***> 写道：
> > 
> > ﻿
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > You are receiving this because you are subscribed to this thread.
> 

已经解决了 一个字符搞错了 修改了就编译通过了
