### ISSUE TITLE
请求添加mlx4_core和mlx5_core驱动程序

### ISSUE THREAD

**Issue by Q2297045667** [sbwml/r4s_build_script#39]
英伟达的ConnectX系列的网卡用的人应该挺多的
编译的时候把这个驱动编译进去
建议默认源使用如下源
src/gz openwrt_base https://dl.openwrt.ai/23.05/packages/x86_64/base/
src/gz openwrt_luci https://dl.openwrt.ai/23.05/packages/x86_64/luci/
src/gz openwrt_packages https://dl.openwrt.ai/23.05/packages/x86_64/packages/
src/gz openwrt_routing https://dl.openwrt.ai/23.05/packages/x86_64/routing/
src/gz openwrt_telephony https://dl.openwrt.ai/23.05/packages/x86_64/telephony/

**Comment by sbwml** [comment]
> 英伟达的ConnectX系列的网卡用的人应该挺多的 编译的时候把这个驱动编译进去

https://github.com/sbwml/r4s_build_script/commit/1980291feb8867a2b8a5bc7e4e36eb570e640919

X86 架构下一个构建会包含 `kmod-mlx4-core` & `kmod-mlx5-core` 驱动模块。在此之前的版本也可以通过软件中心搜索安装。

> 建议默认源使用如下源

这里的 openwrt 固件遵循 github.com/openwrt/openwrt  官方 23.05 libc 以及 system libraries，所以我只能官方软件源或来自openwrt 官方上游的镜像源。至于任何来历不明的软件源是不会直接应用到固件中的。

如果确实有这个需求，你可以自己修改设备的 opkg 安装源。

**Comment by Q2297045667** [comment]
> > 英伟达的ConnectX系列的网卡用的人应该挺多的 编译的时候把这个驱动编译进去
> 
> [1980291](https://github.com/sbwml/r4s_build_script/commit/1980291feb8867a2b8a5bc7e4e36eb570e640919)
> 
> X86 架构下一个构建会包含 `kmod-mlx4-core` & `kmod-mlx5-core` 驱动模块。在此之前的版本也可以通过软件中心搜索安装。
> 
> > 建议默认源使用如下源
> 
> 这里的 openwrt 固件遵循 github.com/openwrt/openwrt 官方 23.05 libc 以及 system libraries，所以我只能使用官方软件源或来自 openwrt 官方上游的镜像源。至于任何来历不明的软件源是不会直接应用到固件中的。
> 
> 如果确实有这个需求，你可以自己修改设备的 opkg 安装源。

好的，万分感谢！
