### ISSUE TITLE
大佬有没有考虑添加 rk3588 的支持，比如r6s/r6c/nanopc t6?

### ISSUE THREAD

**Issue by zhuzhe1983** [sbwml/r4s_build_script#4]
多谢大佬

**Comment by sbwml** [comment]
没有，我是完全很个人的个性化openwrt定制，因为我没有 r6s 这些机器，不会考虑它。

但是你自己基于原生的 openwrt 应该很容易backport rk3588 支持，因为主线 linux 6.4、6.5rc 已经支持 3588 soc 了

**Comment by zhuzhe1983** [comment]
好的，谢谢大佬
