### ISSUE TITLE
一个小问题 全锥型 NAT（NFT、BCM 双方案）

### ISSUE THREAD

**Issue by Q2297045667** [sbwml/r4s_build_script#41]
全锥型 NAT（NFT、BCM 双方案）中的BCM是由那个软件包实现的？
卸载了一部分用不到的软件吧之后发现博通的NAT没了
想重新安装一下
![9b82a566c89eeb2933786b8c4a01b380](https://github.com/user-attachments/assets/b05884eb-31a5-4b76-8cde-38e43902dc70)

**Comment by sbwml** [comment]
brcm-fullcone 由防火墙与内核实现，并非单个独立软件包。但 LuCI 支持上，brcm 没有做独立的功能展示，它必须与 nft-fullcone 功能同时存在（`kmod-nft-fullcone`）才会展示 全锥型 NAT 的 LuCI 菜单。

如果你在 “系统” - “软件包” - “已安装” 中卸载某些软件包导致的选项消失，只能重刷固件恢复功能。同时避免卸载或更新任何固件自带的 kmod、lib、firewall 相关内容。

**Comment by Q2297045667** [comment]
> brcm-fullcone 由防火墙套件与内核实现，并非单个独立软件包。但 LuCI 支持上，brcm 没有做独立的功能展示，它必须与 nft-fullcone 功能同时存在（`kmod-nft-fullcone`）才会展示 全锥型 NAT 的 LuCI 菜单。
> 
> 如果你在 “系统” - “软件包” - “已安装” 中卸载某些软件包导致的选项消失，只能重刷固件恢复功能。同时避免卸载或更新任何固件自带的 kmod、lib、firewall 相关内容。

感谢回复，但是我注意到卸载软件包的时候并没有卸载软件包以外的包，因为我并没有勾选“自动移除未使用的依赖”

**Comment by sbwml** [comment]
虽然我不知道你为什么要卸载内置的包，很显然我猜不到你到底卸载的什么和问题出现的原因。

不过没有关系，我可以给你推荐一个更优秀的固件，与本固件相比，它内置的软件包更少   https://github.com/QiuSimons/YAOF

**Comment by sbwml** [comment]
> 虽然我不知道你为什么要卸载内置的包，很显然我猜不到你到底卸载的什么和问题出现的原因。
> 
> 不过没有关系，我可以给你推荐一个更优秀的固件，与本固件相比，它内置的软件包更少 https://github.com/QiuSimons/YAOF

同时它也支持 brcm fullcone 
![image](https://github.com/user-attachments/assets/13c04b16-7ef5-42c5-ac54-a1b762461833)

**Comment by Q2297045667** [comment]
> > 虽然我不知道你为什么要卸载内置的包，很显然我猜不到你到底卸载的什么和问题出现的原因。
> > 不过没有关系，我可以给你推荐一个更优秀的固件，与本固件相比，它内置的软件包更少 https://github.com/QiuSimons/YAOF
> 
> 同时它也支持 brcm fullcone ![image](https://private-user-images.githubusercontent.com/16485166/348511215-13c04b16-7ef5-42c5-ac54-a1b762461833.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MjE5NjAsIm5iZiI6MTcyMDkyMTY2MCwicGF0aCI6Ii8xNjQ4NTE2Ni8zNDg1MTEyMTUtMTNjMDRiMTYtN2VmNS00MmM1LWFjNTQtYTFiNzYyNDYxODMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDAxNDc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ODU1NzdmOGFlOGNmMGY3YmI3Njc2N2Y3YTQ4YTJjZWE3NDlmODg2MTZlOGQxZjdmNDc5ODcyNDY3OTIwOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._ifKUX4NYiMJh1mFBEezgOLUckqWtyJfqtDghCTiYuw)

只是闲着没事折腾而已，我自己Fork了一个，自己改一改 看看能不能解决这个问题，在编译的时候直接去掉不需要的软件包，不要抛弃我，嘿嘿

**Comment by sbwml** [comment]
其实意义并不大，对于构建完全不熟悉的情况下，自己构建出来 和 你能直接下载到的固件，它们完全是两种东西来的

**Comment by Q2297045667** [comment]
> 其实意义并不大，对于构建完全不熟悉的情况下，自己构建出来 和 你能直接下载到的固件，它们完全是两种东西来的

![817ba6c5c4557d1a4dd26389a434d824](https://github.com/user-attachments/assets/30fdc2da-b41b-4870-af30-60d0559be863)
没事瞎折腾，我去看看构建结果
