### ISSUE TITLE
No rule to make target 'Not', needed by '404'.  Stop

### ISSUE THREAD

**Issue by firefox-half** [sbwml/r4s_build_script#47]
大佬我这个 ubuntu24.4.1编译报这个错，有遇到过吗？我使用22的版本和debian11也是![image](https://github.com/user-attachments/assets/2542a945-ad3b-4152-a449-7493ebccbce1)

**Comment by sbwml** [comment]
![image](https://github.com/user-attachments/assets/ee54f1b0-0e75-4ae3-87f8-a6ca40738874)

**Comment by firefox-half** [comment]
> 如果你对 openwrt 源码不熟悉，我并不推荐你在本地进行构建（因为这意义不大，这个脚本对 openwrt 源码进行全面 hack，意味着每次构建只能通过脚本进行，而无法直接更新源码增量编译）。另外它支持 fork 后使用 runner 在线编译。

嗯嗯好的，谢谢大佬的讲解。不过遇到了 设置 CONFIG_TARGET_ROOTFS_PARTSIZE >27G 的配置，想把r5c的空间占满。fork 的项目，但是老是编译不通过，修改到18G左右才行，哭死
