### ISSUE TITLE
内核模块缺失

### ISSUE THREAD

**Issue by ncwb** [sbwml/r4s_build_script#48]
mwan3使用ip6tables出现unknown option "--set-xmark" 

尝试命令modprobe xt_mark无果

应该是内核模块缺失 请求修复

**Comment by ncwb** [comment]
ip6tables_zz_legacy等也已经安装 问题依旧

**Comment by ncwb** [comment]
此问题在23.05 24.10及内核6.6 6.12上均有复现

**Comment by sbwml** [comment]
已修复

**Comment by ncwb** [comment]
非常感谢大神提供如此好的固件和不辞辛苦的维护

**Comment by ilxp** [comment]
非常感谢大神提供如此好的固件和不辞辛苦的维护！  +100

**Comment by ilxp** [comment]
> 非常感谢大神提供如此好的固件和不辞辛苦的维护

+10000
