### ISSUE TITLE
请求添加NanoPi R6S固件

### ISSUE THREAD

**Issue by adminlte** [sbwml/r4s_build_script#50]

**Comment by sbwml** [comment]
抱歉啊，这里单纯是 **个人自用** OpenWrt 定制脚本，nanopi r6s 不会出现在这里，因为我没有这个机器，我不会添加一个我没有的设备到这里，尽管 openwrt 官方支持它也不会被添加。

做固件我不是专业的，你应该去找那些专业的固件作者或项目。据我了解，nanopi r6s 从来不缺固件，openwrt 官方也支持这个设备。
