### ISSUE TITLE
OTA升级没有反应

### ISSUE THREAD

**Issue by ilxp** [sbwml/r4s_build_script#52]
已经检测到了新固件，点击更新，就卡主没有反映了。

**Comment by ilxp** [comment]
![1729778984780](https://github.com/user-attachments/assets/d7aca1af-d9e6-4116-a10f-9206b01398a0)
![1729779038679](https://github.com/user-attachments/assets/dacc67ad-d6fb-4a8c-b281-a6ca58b24110)

**Comment by sbwml** [comment]
只有 releases 和 minimal 支持 ota，在使用这个功能之前，你应该先考虑下当前固件来源。

发自我的iPhone

**Comment by ilxp** [comment]
这个我是知道的，ota的依赖都有，就是卡主，不明白

**Comment by sbwml** [comment]
你这个问题没有意义，因为你用的固件它并不来自我GitHub Action 产物

发自我的iPhone
