### ISSUE TITLE
luci-app-package-manager报错

### ISSUE THREAD

**Issue by ilxp** [sbwml/r4s_build_script#53]
最新升级的报错。
* pkg_hash_check_unresolved: cannot find dependency luci-app-package-manager for luci-nginx
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-nginx found, but incompatible with the architectures configured
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci:
 * 	luci-app-package-manager
 * opkg_install_cmd: Cannot install package luci.

**Comment by sbwml** [comment]
你只需要 fork 仓库后运行工作流，它就能正确构建出目标固件，且不会出现这个错误。

发自我的iPhone

**Comment by ilxp** [comment]
退回到上一个commit，就能构建出目标固件。
