### ISSUE TITLE
大佬你能修复一下此固件R5C使用mt7921的问题吗

### ISSUE THREAD

**Issue by akaagiao1** [sbwml/r4s_build_script#6]
<img width="2112" alt="image" src="https://github.com/sbwml/r4s_build_script/assets/94331537/613d53de-21ca-4382-ad27-621188ad2119">

**Comment by sbwml** [comment]
nanopi-r5c 涉及到硬件方面的问题我解决不了，因为我没有这个机器测试。这个机器的固件是构建 r5s 时附带出来的一个固件。

按道理 mt7921  不会有问题才对，因为我在 nanopi-r5s 上通过nvme 转接板安装 mt7921，AP 一切正常。

不过你这个情况，我是无法了解到原因的了。你只能换别的固件去了。
