### ISSUE TITLE
关于第三方软件包的添加

### ISSUE THREAD

**Issue by Q2297045667** [sbwml/r4s_build_script#60]
你好，是这样的我想要添加一个第三方包
op官方源没有的包，这需要改动什么？
添加到02-prepare_package.sh里面编译失败

如下
https://github.com/muink/luci-app-natmapt
在02-prepare_package.sh中的内容
```
# luci-app-natmapt
git clone https://$github/muink/luci-app-natmapt package/new/luci-app-natmapt
```

**Comment by sbwml** [comment]
你的操作流程没有问题，至于没法编译建议到插件作者出反馈。

发自我的iPhone

**Comment by Q2297045667** [comment]
> 你的操作流程没有问题，至于没法编译建议到插件作者出反馈。 发自我的iPhone
> […](#)
> 在 2024年11月11日，10:01，Missing_Love ***@***.***> 写道： ﻿ 你好，是这样的我想要添加一个第三方包 op官方源没有的包，这需要改动什么？ 添加到02-prepare_package.sh里面编译失败 如下 https://github.com/muink/luci-app-natmapt 在02-prepare_package.sh中的内容 luci-app-natmapt git clone https://$github/muink/luci-app-natmapt package/new/luci-app-natmapt — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

感谢回复，我先试试

**Comment by dj56959566** [comment]
怎么没有armv7 32位的呢，我的玩克云刷不上😃😃😃😃

**Comment by Q2297045667** [comment]
> 你的操作流程没有问题，至于没法编译建议到插件作者出反馈。 发自我的iPhone
> […](#)
> 在 2024年11月11日，10:01，Missing_Love ***@***.***> 写道： ﻿ 你好，是这样的我想要添加一个第三方包 op官方源没有的包，这需要改动什么？ 添加到02-prepare_package.sh里面编译失败 如下 https://github.com/muink/luci-app-natmapt 在02-prepare_package.sh中的内容 luci-app-natmapt git clone https://$github/muink/luci-app-natmapt package/new/luci-app-natmapt — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

经过反复测试插件并没有什么问题，该插件在其他固件中可以正常编译

**Comment by sbwml** [comment]
> 经过反复测试插件并没有什么问题，该插件在其他固件中可以正常编译

不存在这个可能性。你应该向插件作者获取帮助，luci源码、依赖等问题
