### ISSUE TITLE
请求添加包mihomo及luci-app-mihomo

### ISSUE THREAD

**Issue by Lu-Lucifer** [sbwml/r4s_build_script#61]
请求添加包mihomo及luci-app-mihomo，拜托了

**Comment by ilxp** [comment]
本来就有的。config文件自己看下

**Comment by sbwml** [comment]
如果你是自己编译的话  那么添加   `CONFIG_PACKAGE_luci-app-mihomo=y`  到 24-config-common

如果你是用的现成固件的话，那么可以直接通过 “软件包” 直接搜索安装

**Comment by sbwml** [comment]
看下这里 #74
