### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by ncwb** [sbwml/r4s_build_script#65]
make[2]: *** No rule to make target 'Not', needed by '404'.  Stop.
make[1]: *** [/builder/openwrt/include/toplevel.mk:[9](https://github.com/ncwb/openwrt-x86-64/actions/runs/11905928866/job/33177183139#step:10:10)7: prepare-tmpinfo] Error 2
make: *** [/builder/openwrt/include/toplevel.mk:246: world] Error 2

重新fork后 用自带的yml文件编译 问题仍然复现

**Comment by sbwml** [comment]
GitHub 连接出现问题，等晚上的，改成本地 http 服务。

发自我的iPhone

**Comment by sbwml** [comment]
修复 https://github.com/sbwml/r4s_build_script/commit/a84c446990030f68bb52382cd1a0796115c2ba06

**Comment by ncwb** [comment]
已成功编译验证 感谢！

**Comment by ncwb** [comment]
昨晚添加无线网卡驱动后出现package编译失败
    ERROR: package/kernel/rtl8812au-ct failed to build.

**Comment by sbwml** [comment]
删掉这个源码或者 is not set 即可，rtw88 的 8812au  已经完全适应于openwrt   而不仅限客户端模式

发自我的iPhone

**Comment by Turing-China** [comment]
> 删掉这个源码或者 is not set 即可，rtw88 的 8812au 已经完全适应于openwrt 而不仅限客户端模式 发自我的iPhone
> […](#)
> 在 2024年11月20日，08:12，ncwb ***@***.***> 写道： ﻿ 昨晚添加无线网卡驱动后出现package编译失败 ERROR: package/kernel/rtl8812au-ct failed to build. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

 is not set 还是会提示这个
    ERROR: package/kernel/rtl8812au-ct failed to build.
