### ISSUE TITLE
怎么加入AdGuardHome

### ISSUE THREAD

**Issue by yndzm** [sbwml/r4s_build_script#67]
02-prepare_package.sh里添加了，# luci-app-adguardhome
git clone https://$github/xiaoxiao29/luci-app-adguardhome package/new/luci-app-adguardhome  openwrt/24-config-common里也添加了CONFIG_PACKAGE_luci-app-adguardhome=y，但是编译出来的固件没有。

**Comment by sbwml** [comment]
你不要拉取任何 adg luci 源码，直接添加配置文件编译。

```
CONFIG_PACKAGE_luci-app-adguardhome=y
```

luci-app-adguardhome 来自  kiddin9/openwrt-adguardhome，能不能用一切随缘，我没有测试过。


ps：并不建议在当代 openwrt 上使用这种年久失修的 luci app，它可能更适合 openwrt 21.02 以前的 openwrt。

**Comment by yndzm** [comment]
谢谢，能用。但是这个adguardhome开机就自动启动，luci界面里的启动开关不管用，必须用命令停止，我手动安装的正常。怎么才能换成其他luci源码。

**Comment by sbwml** [comment]
删掉 package/new/custom 目录的源码    拉你自己的

发自我的iPhone
