### ISSUE TITLE
Error compiling quectel-qmi-wwan and fibocom-qmi-wwan with kernel 6.12

### ISSUE THREAD

**Issue by Roxy09099** [sbwml/r4s_build_script#71]
https://github.com/immortalwrt/wwan-packages
https://github.com/immortalwrt/wwan-packages/tree/master/drivers
hope you can add patch for kernel 6.12

make[4]: Entering directory '/builder/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-6.12.1'
  CC [M]  /builder/openwrt/build_dir/target-x86_64_musl/linux-x86_64/quectel-qmi-wwan-1.2.6/qmi_wwan_q.o
../quectel-qmi-wwan-1.2.6/qmi_wwan_q.c:1467:5: warning: no previous prototype for function 'qma_setting_store' [-Wmissing-prototypes]
 1467 | int qma_setting_store(struct device *dev, QMAP_SETTING *qmap_settings, size_t size) {
      |     ^
../quectel-qmi-wwan-1.2.6/qmi_wwan_q.c:1467:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
 1467 | int qma_setting_store(struct device *dev, QMAP_SETTING *qmap_settings, size_t size) {
      | ^
      | static 
../quectel-qmi-wwan-1.2.6/qmi_wwan_q.c:2009:2: error: call to undeclared library function 'strlcpy' with type 'unsigned long (char *, const char *, unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 2009 |         strlcpy(info->driver, driver_name, sizeof(info->driver));
      |         ^
../quectel-qmi-wwan-1.2.6/qmi_wwan_q.c:2009:2: note: include the header <string.h> or explicitly provide a declaration for 'strlcpy'
1 warning and 1 error generated.
make[6]: *** [scripts/Makefile.build:229: /builder/openwrt/build_dir/target-x86_64_musl/linux-x86_64/quectel-qmi-wwan-1.2.6/qmi_wwan_q.o] Error 1
make[5]: *** [/builder/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-6.12.1/Makefile:1936: /builder/openwrt/build_dir/target-x86_64_musl/linux-x86_64/quectel-qmi-wwan-1.2.6] Error 2
make[4]: *** [Makefile:224: __sub-make] Error 2
make[4]: Leaving directory '/builder/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-6.12.1'
make[3]: *** [Makefile:25: /builder/openwrt/build_dir/target-x86_64_musl/linux-x86_64/quectel-qmi-wwan-1.2.6/.built] Error 2
make[3]: Leaving directory '/builder/openwrt/package/5gwwan/drivers/quectel-qmi-wwan'
time: package/5gwwan/drivers/quectel-qmi-wwan/compile#1.38#0.82#2.27
    ERROR: package/5gwwan/drivers/quectel-qmi-wwan failed to build.
make[2]: *** [package/Makefile:179: package/5gwwan/drivers/quectel-qmi-wwan/compile] Error 1
make[2]: Leaving directory '/builder/openwrt'
make[1]: *** [package/Makefile:173: /builder/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/builder/openwrt'
make: *** [/builder/openwrt/include/toplevel.mk:248: world] Error 2
Error: Process completed with exit code 2.

**Comment by sbwml** [comment]
https://github.com/sbwml/r4s_build_script/commit/dbf0a57355d6afa22fc2a5ea0ec1098c92c8295c
