### ISSUE TITLE
编译最新源码报错

### ISSUE THREAD

**Issue by subus0222** [sbwml/r4s_build_script#72]
环境：基于wsl2的docker：ubuntu22.04  
报错日志如下：  
# CC      lib/kobject_uevent.o
  aarch64-openwrt-linux-musl-gcc -Wp,-MMD,lib/.kobject_uevent.o.d -nostdinc -I./arch/arm64/include -I./arch/arm64/include/generated  -I./include -I./arch/arm64/include/uapi -I./arch/arm64/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/compiler-version.h -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -mlittle-endian -DKASAN_SHADOW_SCALE_SHIFT= -fmacro-prefix-map=./= -Werror -std=gnu11 -fshort-wchar -funsigned-char -fno-common -fno-PIE -fno-strict-aliasing -mgeneral-regs-only -DCONFIG_CC_HAS_K_CONSTRAINT=1 -Wno-psabi -mabi=lp64 -fno-asynchronous-unwind-tables -fno-unwind-tables -mbranch-protection=pac-ret -Wa,-march=armv8.5-a -DARM64_ASM_ARCH='"armv8.5-a"' -DKASAN_SHADOW_SCALE_SHIFT= -fno-delete-null-pointer-checks -O2 -fno-allow-store-data-races -fstack-protector -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-stack-clash-protection -falign-functions=4 -fstrict-flex-arrays=3 -fno-strict-overflow -fno-stack-check -fconserve-stack -Wall -Wundef -Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type -Werror=strict-prototypes -Wno-format-security -Wno-trigraphs -Wno-frame-address -Wno-address-of-packed-member -Wmissing-declarations -Wmissing-prototypes -Wframe-larger-than=2048 -Wno-main -Wno-dangling-pointer -Wvla -Wno-pointer-sign -Wcast-function-type -Wno-stringop-overflow -Wno-array-bounds -Wno-alloc-size-larger-than -Wimplicit-fallthrough=5 -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Wenum-conversion -Wextra -Wunused -Wno-unused-but-set-variable -Wno-unused-const-variable -Wno-packed-not-aligned -Wno-format-overflow -Wno-format-truncation -Wno-stringop-truncation -Wno-override-init -Wno-missing-field-initializers -Wno-type-limits -Wno-shift-negative-value -Wno-maybe-uninitialized -Wno-sign-compare -Wno-unused-parameter -g -gdwarf-5 -fno-var-tracking -femit-struct-debug-baseonly -fmacro-prefix-map=/home/subs/r4s_build_script/openwrt/build_dir/target-aarch64_generic_musl=target-aarch64_generic_musl -fno-caller-saves -march=armv8.2-a+crypto+crc -mcpu=cortex-a55+crypto+crc -mtune=cortex-a55 -mstack-protector-guard=sysreg -mstack-protector-guard-reg=sp_el0 -mstack-protector-guard-offset=1256    -DKBUILD_MODFILE='"lib/kobject_uevent"' -DKBUILD_BASENAME='"kobject_uevent"' -DKBUILD_MODNAME='"kobject_uevent"' -D__KBUILD_MODNAME=kmod_kobject_uevent -c -o lib/kobject_uevent.o lib/kobject_uevent.c
lib/kobject_uevent.c:182:5: error: no previous prototype for 'uevent_next_seqnum' [-Werror=missing-prototypes]
  182 | u64 uevent_next_seqnum(void)
      |     ^~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[8]: *** [scripts/Makefile.build:229: lib/kobject_uevent.o] Error 1
make[7]: *** [scripts/Makefile.build:478: lib] Error 2
make[6]: *** [/home/subs/r4s_build_script/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.12.1/Makefile:1936: .] Error 2
make[5]: *** [Makefile:224: __sub-make] Error 2
make[5]: Leaving directory '/home/subs/r4s_build_script/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.12.1'
make[4]: *** [Makefile:25: /home/subs/r4s_build_script/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.12.1/.modules] Error 2
make[4]: Leaving directory '/home/subs/r4s_build_script/openwrt/target/linux/rockchip'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/subs/r4s_build_script/openwrt/target/linux'
time: target/linux/compile#0.69#0.07#1.06
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:32: target/linux/compile] Error 1
make[2]: Leaving directory '/home/subs/r4s_build_script/openwrt'
make[1]: *** [target/Makefile:25: /home/subs/r4s_build_script/openwrt/staging_dir/target-aarch64_generic_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/subs/r4s_build_script/openwrt'
make: *** [/home/subs/r4s_build_script/openwrt/include/toplevel.mk:248: world] Error 2

**Comment by sbwml** [comment]
用 GitHub action 编译
