### ISSUE TITLE
不知道是什么原因CPU老是100占用

### ISSUE THREAD

**Issue by yndzm** [sbwml/r4s_build_script#75]
也没看到网速占用

**Comment by shuangqiao999** [comment]
> 也没看到网速占用
可以先在管理页面查看进程 看看是哪个占用率高

**Comment by shuangqiao999** [comment]
现在编译的x86精简版的固件非常好用 占用率极低 测速时(百兆宽带)似乎就像有硬件转发一样 cpu占用率一直在0.1%-0.4% 开bt时连接数到五万多没有一点卡顿 更高的连接数没试过。之前的固件测速时占用1%-3%波动 感谢老大带来了好用的固件🙏🏻🙏🏻🙏🏻

**Comment by yndzm** [comment]
破案了，passwall负载均衡搞得

**Comment by shuangqiao999** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
