### ISSUE TITLE
USB tethering - USB0 cant detected on interface 

### ISSUE THREAD

**Issue by zero2black** [sbwml/r4s_build_script#76]
I will try build openwrt 24-snapshot but i have problem usb0 not detected on interface.can you help me to solved my problem?

**Comment by sbwml** [comment]
你所说的 USB0 它是一个什么设备？

（请用中文回复，不方便翻译）

**Comment by sbwml** [comment]
你是说它不显示在这里的意思？

![image](https://github.com/user-attachments/assets/9a55f14c-a98c-44c1-8ea0-8f9f448e91ce)
