### ISSUE TITLE
ipv6的禁用

### ISSUE THREAD

**Issue by Turing-China** [sbwml/r4s_build_script#78]
麻烦问下，如何禁用ipv6的编译

**Comment by sbwml** [comment]
这个仓库会强制编译 ipv6 支持的地方只有两处：

1、删除 ipv6 相关依赖： https://github.com/sbwml/default-settings/blob/master/Makefile#L24
2、删除 config 包含 `6` 关键词的全部配置： https://github.com/sbwml/r4s_build_script/blob/master/openwrt/24-config-common

到此，通过这个仓库构建的 OpenWrt 不会强制包含 ipv6 支持。

但并不代表这样构建的固件就不支持 ipv6，OpenWrt 默认会编译 ipv6 的支持库。至于是哪一个部分需要你自己前往 OpenWrt 代码仓库找，因为默认配置不由这个 repo 控制。
