### ISSUE TITLE
OTA在线升级卡在下载100%，然没有没有任何动作了

### ISSUE THREAD

**Issue by ilxp** [sbwml/r4s_build_script#8]
想升级大佬最新6.6.但在线升级卡在100%。如题
![1704020441238](https://github.com/sbwml/r4s_build_script/assets/61609258/0b4e1b98-0e9b-4a81-a7e1-28afceca8f05)

**Comment by sbwml** [comment]
这个问题“一直存在”，原因是 curl 进程在文件下载完成后没有正常退出变成了僵尸进程，随意卡在100%，至于为什么它会变成僵尸进程，目前没有任何头绪。

这种情况只能浏览器去下载固件，通过 openwrt 自带的更新去升级了

**Comment by ilxp** [comment]
明白了。相信大佬能解决。

**Comment by sbwml** [comment]
ota 在线更新目前已从 `curl` 转为自有的 libcurl 库轻量下载器，并且固件下载状态由进程判断变更为进度（100%）判断，这个问题应该会得到根治。

这个修复在下一个固件发布中生效。

**Comment by sbwml** [comment]
已经在最新发布中得到修复
