### ISSUE TITLE
关于XDP-Forwarding

### ISSUE THREAD

**Issue by shuangqiao999** [sbwml/r4s_build_script#80]
你好 老大 看到一个这样的项目 https://github.com/gamemann/XDP-Forwarding 能不能集成到固件里？

**Comment by sbwml** [comment]
这个东西在 openwrt 上能起到什么作用？

另外我的r5s网卡并不支持这个玩意…..


发自我的iPhone

**Comment by shuangqiao999** [comment]
😅😅
