### ISSUE TITLE
想问下为何移除daed集成

### ISSUE THREAD

**Issue by breeze303** [sbwml/r4s_build_script#83]
是它实现效果不理想吗？

**Comment by sbwml** [comment]
daed 支持通过 **系统** - **软件包**  搜索安装。

![image](https://github.com/user-attachments/assets/3f15675a-b719-44eb-ab9a-009f956e2131)

不内置的原因是经过用户调查，这个插件使用频率极低。真实在 OpenWrt 路由系统上与其它科学插件对比并没有非常明显的优势，且不支持 PPPoE 拨号时代理本机流量。出于固件体积大小的考虑，所以不再内置。

**Comment by breeze303** [comment]
十分感激解答疑惑
