### ISSUE TITLE
软件包更新报错

### ISSUE THREAD

**Issue by yndzm** [sbwml/r4s_build_script#84]
Collected errors:
 * opkg_download: Failed to download https://ghp.ci/raw.githubusercontent.com/sbwml/openwrt_core/x86_64/6.12.4~df1d3abd1b4a8c85897ac5742012fbcf-r1/Packages.gz, wget returned 4.
 * opkg_download: Check your network settings and connectivity.
opkg update 命令失败了 ，代码为 1。

**Comment by sbwml** [comment]
编辑软件源最后一行   删除ghp.ci   就好了

发自我的iPhone
