### ISSUE TITLE
这个可以开启吗？

### ISSUE THREAD

**Issue by shuangqiao999** [sbwml/r4s_build_script#85]
​# CONFIG_KERNEL_PREEMPT_RT is not set
老大  这个开启与不开启有什么区别？

**Comment by sbwml** [comment]
Linux 实时系统，目前不稳定（aarch64）。

发自我的iPhone

**Comment by shuangqiao999** [comment]
👌🏻👌🏻👌🏻

**Comment by shuangqiao999** [comment]
我试了一下 开启实时系统和之前一样 没有出现不稳定的情况 （x86) 固件尺寸稍微大点

**Comment by sbwml** [comment]
你随意

**Comment by shuangqiao999** [comment]
使用情况反馈: 用ping工具 tcp模式ping80端口 间隔1毫秒 丢包2%  每个包发送最低和最高用时均降到几毫秒 平均用时在4到5毫秒左右 延迟降低非常明显 没有开启rt时平均用时为300多毫秒 但是不会丢包 间隔10毫秒丢包1% 间隔20毫秒不丢包
