### ISSUE TITLE
保存并应用无反应

### ISSUE THREAD

**Issue by Karmylr** [sbwml/r4s_build_script#86]
从 https://github.com/sbwml/builder/releases/tag/v24.10.0-rc3 下载的固件，在网络-防火墙页面点保存并应用，只会转圈，没有反应
![image](https://github.com/user-attachments/assets/e33f0f71-86b0-4e57-ba73-76e9fabc3a19)

**Comment by sbwml** [comment]
可能是rc3 的bug      回去我试试

发自我的iPhone

**Comment by sbwml** [comment]
是 rc3 的 bug，上游已经有人反馈了 [ #17333](https://github.com/openwrt/openwrt/issues/17333)

**Comment by sbwml** [comment]
修复版本已经在构建 （ https://github.com/sbwml/builder/actions/runs/12441216843 ），大约3小时后会得到 OTA 更新。
