### ISSUE TITLE
手机登录界面输入密码后点击登录误进入github

### ISSUE THREAD

**Issue by yndzm** [sbwml/r4s_build_script#87]
不能截图，望修复

**Comment by sbwml** [comment]
什么意思？

发自我的iPhone

**Comment by yndzm** [comment]
就是用手机浏览器登录的时候，打上密码点击登录会跳转到github

**Comment by yndzm** [comment]
填写密码的地方刚好被Powered by LuCI openwrt-24.10 branch (24.356.61360~b43aea7)
/ OpenWrt 24.10-SNAPSHOT r28204-975811921e这行挡住

**Comment by sbwml** [comment]
Safari、Chrome 模拟移动端未复现。

发自我的iPhone

**Comment by yndzm** [comment]
谷歌浏览器没这问题，via，小米浏览器都出现了

**Comment by sbwml** [comment]
建议去 argon 主题仓库问问。我这里没法复现，或者你换openwrt 默认主题来用。

发自我的iPhone

**Comment by sbwml** [comment]
已经将 argon 主题在浏览器高度小于 530像素时隐藏页脚。如果你依然能遇到这种情况。那么你应该使用 OpenWrt 自带的 Bootstrap 主题。或者应该考虑是否真的有必要在这种分辨率的设备上去登录 LuCI。

**Comment by yndzm** [comment]
老大，神速啊，完美了
