### ISSUE TITLE
ENABLE_LOCAL_KMOD=y /usr/share/openwrt_core/ 中缺少 Packages.gz

### ISSUE THREAD

**Issue by Kaizz983** [sbwml/r4s_build_script#88]
ls /usr/share/openwrt_core/kmod-xdp*
/usr/share/openwrt_core/kmod-xdp-sockets-diag_6.12.1-r1_x86_64.ipk
ls /usr/share/openwrt_core/Package*
ls: cannot access '/usr/share/openwrt_core/Package*': No such file or directory
opkg update
Downloading file:///usr/share/openwrt_core/Packages.gz
*** Failed to download the package list from file:///usr/share/openwrt_core/Packages.gz
Collected errors:
 * copy_file: ///usr/share/openwrt_core/Packages.gz: No such file or directory.
 * file_copy: Failed to copy file ///usr/share/openwrt_core/Packages.gz to /var/opkg-lists/openwrt_core.

**Comment by sbwml** [comment]
ipk 全部都有   就包信息不存在？

发自我的iPhone
